name: joplin_web_clone
description: "A web-based note-taking application inspired by Joplin"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  archive: ^4.0.7
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  provider: ^6.1.5+1
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/db.json
